### PR TITLE
Make oss-migration play nicely with apiext.

### PR DESCRIPTION
**Pull request by kflynn**
It needed to include many things that it wasn't including.

Side note: we really need to document how the require.yaml's work.

Signed-off-by: Flynn <flynn@datawire.io>

### CODE REVIEW

**Review by LukeShu — CHANGES_REQUESTED** [review]
The order in the resulting YAML matches the order in `require.yaml`.  And the `ServiceAccount` needs to exist before any `(Cluster)RoleBinding`s that bind to it.

**Comment by LukeShu** [comment]
See also: `k8s-config/*/require.yaml` in emissary.git

**Comment by LukeShu** [comment]
Also, the `Service` is missing?

**Comment by LukeShu** [comment]
This might already be a problem with `rel/v2.1.0`, but CI is failing because
```
Error: the lock file (Chart.lock) is out of sync with the dependencies file (Chart.yaml). Please update the dependencies
```
A `helm dependency update` is in order.

**Comment by kflynn** [comment]
Superseded by #34.

**Pull request closed without merging**
